baseURL = "https://italovietro.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Italo Vietro"
theme = "hermit"
pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
googleAnalytics = "UA-5628814-4"
disqusShortname = "italovietro"

[author]
  name = "Italo Vietro"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "SRE Enthusiast, Distributed Systems Engineer, and Coffee Lover"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "twitter"
    url   = "https://twitter.com/italolelis/"

  [[params.social]]
    name = "linkedin"
    url   = "https://www.linkedin.com/in/italolelis/"

  [[params.social]]
    name = "github"
    url   = "https://github.com/italolelis/"

  [[params.social]]
    name = "stack-overflow"
    url = "https://stackoverflow.com/story/italolelis"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "blog/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20

  [[menu.main]]
    name = "Manager"
    url = "manager/"
    weight = 30
